apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: 593635309133.dkr.ecr.eu-west-2.amazonaws.com/go-conc-app:1.2
          ports:
            - containerPort: 8080
